//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file was automatically generated by RisohEditor.
// SimpleJP_res.rc

#define IDC_STATIC                          -1

#define IDD_LOWER                           1
#define IDD_UPPER                           2
#define IDD_DIGITS                          3
#define IDD_HIRAGANA                        4
#define IDD_KATAKANA                        5

#define IDS_KANA                            100
#define IDS_ABC                             101
#define IDS_DIGITS                          102
#define IDS_HIRAGANA                        103
#define IDS_KATAKANA                        104

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
