//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file was automatically generated by RisohEditor.
// SimpleNumPad_res.rc

#define IDC_STATIC                          -1

#define IDD_NUMPAD                          100

#define IDS_KANA                            100
#define IDS_ABC                             101
#define IDS_DIGITS                          102
#define IDS_HIRAGANA                        103
#define IDS_KATAKANA                        104
#define IDS_CAPS                            105
#define IDS_SHIFT                           106
#define IDS_ENTER                           107
#define IDS_CONV                            108
#define IDS_NOCONV                          109
#define IDS_NEXTCAND                        110
#define IDS_PREVCAND                        111
#define IDS_BS                              112
#define IDS_DEL                             113
#define IDS_LEFT                            114
#define IDS_RIGHT                           115
#define IDS_SMALL                           116
#define IDS_CTRL                            117
#define IDS_ALT                             118
#define IDS_WIN                             119
#define IDS_SCROLL                          120
#define IDS_INS                             121
#define IDS_HOME                            122
#define IDS_END                             123
#define IDS_PGUP                            124
#define IDS_PGDN                            125
#define IDS_UP                              126
#define IDS_DOWN                            127
#define IDS_PAUSE                           128
#define IDS_ESC                             129
#define IDS_APPNAME                         130

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
