//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file was automatically generated by RisohEditor.
// StdJP_res.rc

#define IDC_STATIC                          -1

#define IDD_NORMAL                          100
#define IDD_CAPITAL                         101
#define IDD_SHIFTED                         102
#define IDD_CAPITAL_SHIFTED                 103
#define IDD_ROMA_NORMAL                     108
#define IDD_ROMA_CAPITAL                    109
#define IDD_ROMA_SHIFTED                    110
#define IDD_ROMA_CAPITAL_SHIFTED            111
#define IDD_HIRA_NORMAL                     116
#define IDD_HIRA_SHIFTED                    117
#define IDD_KATA_NORMAL                     120
#define IDD_KATA_SHIFTED                    121

#define IDS_KANA                            100
#define IDS_ABC                             101
#define IDS_DIGITS                          102
#define IDS_HIRAGANA                        103
#define IDS_KATAKANA                        104
#define IDS_CAPS                            105
#define IDS_SHIFT                           106
#define IDS_ENTER                           107
#define IDS_CONV                            108
#define IDS_NOCONV                          109
#define IDS_NEXTCAND                        110
#define IDS_PREVCAND                        111
#define IDS_BS                              112
#define IDS_DEL                             113
#define IDS_LEFT                            114
#define IDS_RIGHT                           115
#define IDS_SMALL                           116
#define IDS_CTRL                            117
#define IDS_ALT                             118
#define IDS_WIN                             119
#define IDS_SCROLL                          120
#define IDS_INS                             121
#define IDS_HOME                            122
#define IDS_END                             123
#define IDS_PGUP                            124
#define IDS_PGDN                            125
#define IDS_UP                              126
#define IDS_DOWN                            127
#define IDS_PAUSE                           128
#define IDS_ESC                             129
#define IDS_F1                              130
#define IDS_F2                              131
#define IDS_F3                              132
#define IDS_F4                              133
#define IDS_F5                              134
#define IDS_F6                              135
#define IDS_F7                              136
#define IDS_F8                              137
#define IDS_F9                              138
#define IDS_F10                             139
#define IDS_F11                             140
#define IDS_F12                             141
#define IDS_TAB                             142
#define IDS_APPS                            143
#define IDS_PRINT                           144
#define IDS_BREAK                           145
#define IDS_NUM                             146
#define IDS_HAN_ZEN                         147
#define IDS_APPNAME                         148

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
